const products = [
	{
		_id: '1',
		name: 'adidas Classics Black Jacket',
		image: '/images/adidas/jacket/adidas-blk-jkt.jpg',
		description:
			' Classic adidas energy abounds through considered details including 3-Stripes down the sleeves and an embroidered Trefoil logo on the chest. Made from a comfortable cotton-polyester blend, this fresh take on a well-loved design is the perfect addition to any wardrobe.',
		brand: 'adidas',
		category: 'Jacket',
		price: 89.99,
		countInStock: 15,
		rating: 4.0,
		numReviews: 4,
	},
	{
		_id: '2',
		name: 'ADICOLOR Classics Red TRACK JACKET',
		image: '/images/adidas/jacket/adidas-red-jkt.jpg',
		description:
			'This signature track jacket nails a timeless look. An embroidered Trefoil logo adds a touch of pizzazz, and the supremely soft cotton blend makes it perfect for everyday wear. With a slim fit and full zip, it gives any outfit a dash of attitude',
		brand: 'adidas',
		category: 'Jacket',
		price: 69.99,
		countInStock: 10,
		rating: 4.0,
		numReviews: 6,
	},
	{
		_id: '3',
		name: 'adidas TREFOIL Gray Sweat Pants',
		image: '/images/adidas/bottom/adidas-pants.jpg',
		description:
			'Reimagine comfort and step up your loungewear game with the adidas Essentials+ Reverse Material sweat pants. Crafted from a soft fleece, these pants fit close to the body but still give you enough room to move freely.',
		brand: 'adidas',
		category: 'Pants',
		price: 59.99,
		countInStock: 5,
		rating: 3.5,
		numReviews: 3,
	},
	{
		_id: '4',
		name: 'ADICOLOR TREFOIL White Hoodie',
		image: '/images/adidas/sweatshirt/adidas-wht-swt.jpg',
		description:
			'A CLASSIC HOODIE FOR EFFORTLESS EVERYDAY STYLE. This adidas hoodie adds cool energy to your look',
		brand: 'adidas',
		category: 'Sweat Shirt',
		price: 89.99,
		countInStock: 10,
		rating: 5.0,
		numReviews: 3,
	},
	{
		_id: '5',
		name: 'ADICOLOR CREW RED Sweatshirt',
		image: '/images/adidas/sweatshirt/adidas-res-swt.jpg',
		description:
			'A MINIMALIST PULLOVER WITH CLEAN, STRAIGHTFORWARD ADIDAS DNA.',
		brand: 'adidas',
		category: 'Sweat Shirt',
		price: 69.99,
		countInStock: 7,
		rating: 3.5,
		numReviews: 2,
	},
	{
		_id: '6',
		name: 'Adidas CLASSICS White TREFOIL TEE',
		image: '/images/adidas/tee/adidas-wht-tee.jpg',
		description:
			"Refresh your casual look with a modern classic in comfortable single jersey fabric. Not too loose or too tight, it's perfect for day-to-day wear.",
		brand: 'adidas',
		category: 'Tee',
		price: 49.99,
		countInStock: 0,
		rating: 4.0,
		numReviews: 4,
	},
	{
		_id: '7',
		name: 'Adidas CLASSICS White TREFOIL TEE',
		image: '/images/adidas/tee/adidas-wht-tee.jpg',
		description:
			"Refresh your casual look with a modern classic in comfortable single jersey fabric. Not too loose or too tight, it's perfect for day-to-day wear.",
		brand: 'adidas',
		category: 'Tee',
		price: 49.99,
		countInStock: 0,
		rating: 3.5,
		numReviews: 4,
	},
	{
		_id: '8',
		name: 'Nike Oversized White Jacket',
		image: '/images/nike/jacket/nike-wht-jkt.jpg',
		description:
			'Keep cozy in this oversized faux-fur puffer. Synthetic down helps keep you warm and cozy on cold days.',
		brand: 'Nike',
		category: 'Jacket',
		price: 109.99,
		countInStock: 10,
		rating: 5.0,
		numReviews: 4,
	},
	{
		_id: '9',
		name: 'Nike Sportswear Windrunner',
		image: '/images/nike/jacket/nike-red-jkt.jpg',
		description:
			'The Nike Sportswear Windrunner Jacket updates our first running windbreaker with lightweight fabric made from recycled materials.',
		brand: 'Nike',
		category: 'Jacket',
		price: 59.99,
		countInStock: 7,
		rating: 3.5,
		numReviews: 4,
	},
	{
		_id: '10',
		name: 'Nike CLASSICS Black Sweat Pants',
		image: '/images/nike/bottom/nike-blk-pants.jpg',
		description:
			"Your workouts don't stop when the cool weather begins. And Designed to keep you feeling warm and comfortable.",
		brand: 'Nike',
		category: 'Pants',
		price: 79.99,
		countInStock: 10,
		rating: 2.5,
		numReviews: 6,
	},
	{
		_id: '11',
		name: 'Nike CLASSICS Black Hoodie',
		image: '/images/nike/sweatshirt/nike-blk-hoodie.jpg',
		description:
			'This sweat-wicking hoodie combines a classic look with the feel of modern performance for beyond the basketball court.',
		brand: 'Nike',
		category: 'Sweat Shirt',
		price: 99.99,
		countInStock: 8,
		rating: 3.5,
		numReviews: 4,
	},
	{
		_id: '12',
		name: 'Nike CLASSICS MOS Sweatshirt',
		image: '/images/nike/sweatshirt/nike-mos-sweat.jpg',
		description:
			'This Sweatshirt is a perfect match with any item.Pick your go-to color combo and pair it up with your favorite sneakers.',
		brand: 'Nike',
		category: 'Sweat Shirt',
		price: 79.99,
		countInStock: 8,
		rating: 4.5,
		numReviews: 4,
	},
	{
		_id: '13',
		name: 'adidas CLASSICS Black Knit Cap',
		image: '/images/cap/adidas-blk-knit.jpg',
		description:
			"Whatever the reason is cold, style, questionable hair day, there's no wrong one with this adidas beanie.",
		brand: 'adidas',
		category: 'Cap',
		price: 19.99,
		countInStock: 0,
		rating: 4.0,
		numReviews: 3,
	},
	{
		_id: '14',
		name: 'JANSPORT Back To School Black Backpack',
		image: '/images/backpack/jansport-bp.jpg',
		description:
			" Yes! It's time to Back To School!! You need a Spacious BACKPACK WITH A CLASSIC DESIGN.",
		brand: 'JANSPORT',
		category: 'Backpack',
		price: 49.99,
		countInStock: 5,
		rating: 4.0,
		numReviews: 10,
	},
	{
		_id: '15',
		name: 'KANKEN Stylish Greenish Backpack',
		image: '/images/backpack/kanken-grey-bp.jpg',
		description:
			'This Stylish backpack fit anywhere. It takes you all over the world.',
		brand: 'KANKEN',
		category: 'Backpack',
		price: 129.99,
		countInStock: 8,
		rating: 3.5,
		numReviews: 3,
	},
	{
		_id: '16',
		name: 'adidas red  Stadium Backpack',
		image: '/images/backpack/adidas-red-bp.jpg',
		description:
			'Keep all your workout gear separated and organized with this stadium backpack. Multiple pockets give you lots of options for carrying electronics, training shoes and water bottles.',
		brand: 'adidas',
		category: 'Backpack',
		price: 59.99,
		countInStock: 10,
		rating: 2.5,
		numReviews: 4,
	},
];

export default products;
